---

# -------------------------------------------------------------------------------------------------
# Job Name
# -------------------------------------------------------------------------------------------------
name: params


# -------------------------------------------------------------------------------------------------
# Custom Variables
# -------------------------------------------------------------------------------------------------
env:
  MATRIX: >-
    [
      {
        "NAME":    "mysql",
        "VERSION": ["8.0", "8.2", "8.3"],
        "ARCH":    ["linux/amd64", "linux/arm64"]
      },
      {
        "NAME":    "mariadb",
        "VERSION": ["10.4", "10.5", "10.6", "10.11", "11.0", "11.1", "11.2", "11.3"],
        "ARCH":    ["linux/amd64", "linux/arm64"]
      },
      {
        "NAME":    "percona",
        "VERSION": ["5.7", "8.0"],
        "ARCH":    ["linux/amd64"]
      }
    ]


# -------------------------------------------------------------------------------------------------
# When to run
# -------------------------------------------------------------------------------------------------
on:
  workflow_call:
    outputs:
      matrix:
        description: "The determined version matrix"
        value: ${{ jobs.params.outputs.matrix }}
      refs:
        description: "The determined git ref matrix (only during scheduled run)"
        value: ${{ jobs.params.outputs.refs }}
    inputs:
      matrix:
        description: 'The version build matrix as JSON string ( list of objects: [{NAME, VERSION[], ARCH[]}] ).'
        required: false
        type: string
      default_branch:
        description: 'The default branch of this repository to fetch latest tags from.'
        required: false
        default: ${{ github.event.repository.default_branch }}
        type: string
      branches:
        description: 'Comma separated list of branches to create build matrix for.'
        required: false
        default: ${{ github.event.repository.default_branch }}
        type: string

jobs:
  params:
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      refs: ${{ steps.set-refs.outputs.matrix }}

    steps:
      - name: "[DEBUG] Workflow Inputs"
        shell: bash
        run: |
          echo 'matrix: ${{ inputs.matrix }} '
          echo 'default_branch: ${{ inputs.default_branch }} '
          echo 'branches: ${{ inputs.branches }} '

      - name: "[Set-Output] Matrix"
        id: set-matrix
        env:
          MATRIX: ${{ inputs.matrix || env.MATRIX }}
        run: |
          echo "matrix=$( echo '${{ env.MATRIX }}' | jq -M -c )" >> $GITHUB_OUTPUT

      - name: "[Set-Output] Matrix 'Refs' (master branch and latest tag)"
        id: set-refs
        uses: cytopia/git-ref-matrix-action@v0.1.13
        with:
          repository_default_branch: ${{ inputs.default_branch }}
          branches: ${{ inputs.branches }}
          num_latest_tags: 1
        if: github.event_name == 'schedule'

      - name: "[DEBUG] Show settings'"
        run: |
          echo 'Matrix'
          echo '--------------------'
          echo '${{ steps.set-matrix.outputs.matrix }}'
          echo

          echo 'Matrix: Refs'
          echo '--------------------'
          echo '${{ steps.set-matrix-refs.outputs.matrix }}'
          echo
